Ch04 sunwoo
Acka1357/codingtest-java-20 pull request #8
Opened 2023-03-25 05:43 UTC by gbe0808

2023-03-26 03:25 UTC, Eucha09 reviewed
탭이랑 scanf 서식 확인부탁드립니다

2023-03-26 03:25 UTC, Eucha09 commented on Part1_강의자료/Ch04_전체탐색_시뮬레이션/문제별코드/11005_진법변환2/11005.cpp
> +    reverse(str.begin(), str.end());
탭 수정해주세요

2023-03-26 03:25 UTC, Eucha09 commented on Part1_강의자료/Ch04_전체탐색_시뮬레이션/문제별코드/1110_더하기사이클/1110.cpp
> +    } while (cur != N);
do while문 사용 가능한가요?

2023-03-26 03:25 UTC, Eucha09 commented on Part1_강의자료/Ch04_전체탐색_시뮬레이션/문제별코드/1110_더하기사이클/1110.cpp
> +    int N, len = 0, cur;
입력받는 변수는 전역으로 선언할건지 확인해주시면 좋겠습니다

2023-03-26 03:25 UTC, Eucha09 commented on Part1_강의자료/Ch04_전체탐색_시뮬레이션/문제별코드/2309_일곱난쟁이/2309.cpp
> +        scanf(" %d", &dwarf[i]);
" %d" -> "%d
```suggestion
        scanf("%d", &dwarf[i]);
```

2023-03-26 03:25 UTC, Eucha09 commented on Part1_강의자료/Ch04_전체탐색_시뮬레이션/문제별코드/2817_ALPS식투표/2817.cpp
> +int	name[30];
탭 수정해주세요

2023-03-26 03:25 UTC, Eucha09 commented on Part1_강의자료/Ch04_전체탐색_시뮬레이션/문제별코드/2817_ALPS식투표/2817.cpp
> +    scanf(" %d %d", &X, &N);
```suggestion
    scanf("%d %d", &X, &N);
```

2023-03-26 03:25 UTC, Eucha09 commented on Part1_강의자료/Ch04_전체탐색_시뮬레이션/문제별코드/3085_사탕게임/3085.cpp
> +    scanf(" %d", &N);
```suggestion
    scanf("%d", &N);
```

2023-03-26 03:25 UTC, Eucha09 commented on Part1_강의자료/Ch04_전체탐색_시뮬레이션/문제별코드/3085_사탕게임/3085.cpp
> +        scanf(" %s", board[i]);
```suggestion
        scanf("%s", board[i]);
```

2023-03-26 03:25 UTC, Eucha09 commented on Part1_강의자료/Ch04_전체탐색_시뮬레이션/문제별코드/2309_일곱난쟁이/2309.cpp
> +
마지막 공백 없애주세요

2023-03-26 03:25 UTC, Eucha09 commented on Part1_강의자료/Ch04_전체탐색_시뮬레이션/문제별코드/1730_판화/1730.cpp
> +    scanf(" %d %s", &N, command);
```suggestion
    scanf("%d %s", &N, command);
```

2023-03-26 03:25 UTC, Eucha09 commented on Part1_강의자료/Ch04_전체탐색_시뮬레이션/문제별코드/1233_주사위/1233.cpp
> +        scanf(" %d", &S[i]);
```suggestion
        scanf("%d", &S[i]);
```

2023-03-26 03:25 UTC, Eucha09 commented on Part1_강의자료/Ch04_전체탐색_시뮬레이션/문제별코드/1120_문자열/1120.cpp
> +    scanf(" %s %s", A, B);
%s 앞에 공백 필요한건지 확인해주세요

2023-03-26 04:45 UTC, gbe0808 commented on Part1_강의자료/Ch04_전체탐색_시뮬레이션/문제별코드/1110_더하기사이클/1110.cpp
> +    } while (cur != N);
현정선배도 두와일쓰심

2023-03-30 14:27 UTC, Acka1357 requested changes

2023-03-30 14:27 UTC, Acka1357 commented on Part1_강의자료/Ch04_전체탐색_시뮬레이션/문제별코드/1730_판화/1730.cpp
> +                board[cur.first][cur.second] |= 1;
초반챕터라, 사전지식이 추가로 필요한 비트 연산은 지양해주세요.

2023-03-30 14:27 UTC, Acka1357 commented on Part1_강의자료/Ch04_전체탐색_시뮬레이션/문제별코드/1730_판화/1730.py
> +            print(".", end="")
비트연산을 빼면 달라지겠지만, 저라면 기왕 [0,3]으로 만든거 이렇게 사용했을 것 같아요.
```
trail_map = {0: ".", 1: "|", 2: "-", 3: "+"}
for row in board:
    print("".join(trail_map[idx] for idx in row))
```
```
for row in board:
    print("".join(".|-+"[idx] for idx in row))
```

2023-03-30 14:27 UTC, Acka1357 commented on Part1_강의자료/Ch04_전체탐색_시뮬레이션/문제별코드/2817_ALPS식투표/2817.cpp
> +set<score> scores;
아직 set을 다루기 전 파트입니다. 이번 챕터까지는 가급적 배열의 사용 부탁드려요.
set을 쓰셨다는건 문제에서 score가 모두 다르다는 조건을 알기 때문일텐데, vector같은거 두고 굳이 set을 쓴건 이유가 있나요?

2023-04-01 14:24 UTC, merged