Ch05 sunwoo
Acka1357/codingtest-java-20 pull request #9
Opened 2023-03-26 01:57 UTC by gbe0808

2023-04-01 08:11 UTC, Eucha09 reviewed
확인부탁드립니다

2023-04-01 08:11 UTC, Eucha09 commented on Part1_강의자료/Ch05_정렬/문제별코드/1181_단어정렬/1181.cpp
> +    scanf(" %d", &N);
```suggestion
    scanf("%d", &N);
```

2023-04-01 08:11 UTC, Eucha09 commented on Part1_강의자료/Ch05_정렬/문제별코드/1181_단어정렬/1181.cpp
> +    for (int i = 0; i < N; ++i)
```suggestion
    for (int i = 0; i < N; i++)
```

2023-04-01 08:11 UTC, Eucha09 commented on Part1_강의자료/Ch05_정렬/문제별코드/1181_단어정렬/1181.cpp
> +        scanf(" %s", str);
```suggestion
        scanf("%s", str);
```

2023-04-01 08:11 UTC, Eucha09 commented on Part1_강의자료/Ch05_정렬/문제별코드/18310_안테나/18310.cpp
> +	scanf(" %d", &N);
```suggestion
	scanf("%d", &N);
```

2023-04-01 08:11 UTC, Eucha09 commented on Part1_강의자료/Ch05_정렬/문제별코드/18310_안테나/18310.cpp
> +	for (int i = 0; i < N; ++i)
```suggestion
	for (int i = 0; i < N; i++)
```

2023-04-01 08:11 UTC, Eucha09 commented on Part1_강의자료/Ch05_정렬/문제별코드/18310_안테나/18310.cpp
> +		scanf(" %lld", &h);
```suggestion
		scanf("%lld", &h);
```

2023-04-01 08:11 UTC, Eucha09 commented on Part1_강의자료/Ch05_정렬/문제별코드/18870_좌표압축/18870_map.cpp
> +    scanf(" %d", &N);
```suggestion
    scanf("%d", &N);
```

2023-04-01 08:11 UTC, Eucha09 commented on Part1_강의자료/Ch05_정렬/문제별코드/18870_좌표압축/18870_map.cpp
> +map<int, vector<int> > mp;
```suggestion
map<int, vector<int>> mp;
```

2023-04-01 08:11 UTC, Eucha09 commented on Part1_강의자료/Ch05_정렬/문제별코드/18870_좌표압축/18870_map.cpp
> +        scanf(" %d", &arr[i]);
```suggestion
        scanf("%d", &arr[i]);
```

2023-04-01 08:11 UTC, Eucha09 commented on Part1_강의자료/Ch05_정렬/문제별코드/18310_안테나/18310.cpp
> +	return 0;
파일 전체 탭 수정

2023-04-01 08:11 UTC, Eucha09 commented on Part1_강의자료/Ch05_정렬/문제별코드/18870_좌표압축/18870_map.cpp
> +        ++i;
```suggestion
        i++;
```

2023-04-01 08:11 UTC, Eucha09 commented on Part1_강의자료/Ch05_정렬/문제별코드/1931_회의실배정/1931.cpp
> +}
파일전체 탭 수정

2023-04-01 08:11 UTC, Eucha09 commented on Part1_강의자료/Ch05_정렬/문제별코드/18870_좌표압축/18870.cpp
> +} coord;
```suggestion
typedef struct {
    int num;
    int idx;
} coord;
```

2023-04-01 08:11 UTC, Eucha09 commented on Part1_강의자료/Ch05_정렬/문제별코드/7785_회사에있는사람/7785.cpp
> +    scanf(" %d", &N);
```suggestion
    scanf("%d", &N);
```

2023-04-01 08:11 UTC, Eucha09 commented on Part1_강의자료/Ch05_정렬/문제별코드/7785_회사에있는사람/7785.cpp
> +    }
```suggestion
    for (int i = 0; i < N; i++)
    {
        scanf("%s %s", name, log);
        if (strcmp(log, "enter") == 0)
            st.insert(name);
        else
            st.erase(st.find(name));
    }
```

2023-04-01 08:11 UTC, Eucha09 commented on Part1_강의자료/Ch05_정렬/문제별코드/7785_회사에있는사람/7785.cpp
> +
```suggestion
```

2023-04-05 05:24 UTC, Eucha09 commented on Part1_강의자료/Ch05_정렬/문제별코드/1931_회의실배정/1931.cpp
> +    printf("%long longd\n", res);
long long 수정

2023-04-07 16:51 UTC, Acka1357 requested changes

2023-04-07 16:51 UTC, Acka1357 commented on Part1_강의자료/Ch05_정렬/문제별코드/1181_단어정렬/1181.cpp
> +    vec.erase(unique(vec.begin(), vec.end()), vec.end());
각 문제에서 라이브러리 사용 전에 익혔으면 하는 것들이 있는데, 이 문제는 정렬을 통한 중복 제거가 포함됩니다.
이후 문제에서는 자유롭게 사용하셔도 되지만 이 문제는 `erase(unique)` 대신 정렬 후 출력으로 중복 제거로 사용해주세요.

2023-04-07 16:51 UTC, Acka1357 commented on Part1_강의자료/Ch05_정렬/문제별코드/1181_단어정렬/1181.py
> +lst = list(set(lst))
C++ 코멘트와 동일하며, set이 이번 단원에서 다뤄지긴하나 회사에 있는 사람 이후부터 사용되기 때문에 이 문제만 정렬을 통한 중복 제거로 사용해주세요.

2023-04-07 16:51 UTC, Acka1357 commented on Part1_강의자료/Ch05_정렬/문제별코드/18310_안테나/18310.cpp
> +    vector<long long> house;
`long long`일 이유가 있나요?

2023-04-07 16:51 UTC, Acka1357 commented on Part1_강의자료/Ch05_정렬/문제별코드/18870_좌표압축/18870.cpp
> +} coord;
@Eucha09  두 사람 struct 정의하는 부분에 대한 스타일을 논의해서 맞춰주세요.
C++을 사용하기에 은찬이쪽에 맞추는게 좀 더 좋아보입니다.

2023-04-07 16:51 UTC, Acka1357 commented on Part1_강의자료/Ch05_정렬/문제별코드/18870_좌표압축/18870.cpp
> +    sort(arr.begin(), arr.end(), cmp);
일회용 Compare라면 lambda를 적용해보면 좋을 것 같습니다.
```
    sort(arr.begin(), arr.end(), [](const Coord& a, const Coord& b) {
        return a.num < b.num;
    });
```

2023-04-07 16:51 UTC, Acka1357 commented on Part1_강의자료/Ch05_정렬/문제별코드/18870_좌표압축/18870.py
> +st = sorted(list(set(li)))
`st = sorted(set(li))` 만해도 충분합니다.

2023-04-07 16:51 UTC, Acka1357 commented on Part1_강의자료/Ch05_정렬/문제별코드/18870_좌표압축/18870.py
> +dic = {st[i] : i for i in range(len(st))}
알고있겠지만 enumerate도 사용할 수 있습니다.
`dic = {num: i for i, num in enumerate(st)}`

2023-04-07 16:51 UTC, Acka1357 commented on Part1_강의자료/Ch05_정렬/문제별코드/18870_좌표압축/18870_map.cpp
> +map<int, vector<int>> mp;
아마 이전에 작성해둔 코드였을텐데, 이번 챕터부터 전역변수 지양을 위해 수정 부탁드립니다.

2023-04-07 16:51 UTC, Acka1357 commented on Part1_강의자료/Ch05_정렬/문제별코드/18870_좌표압축/18870.py
> +    print(dic[i], end=' ')
`print(' '.join([str(dic[num]) for num in li]))`

2023-04-07 16:51 UTC, Acka1357 commented on Part1_강의자료/Ch05_정렬/문제별코드/18870_좌표압축/18870.cpp
> +    arr.resize(N);
```
vector<int> ans(N);
vector<coord> arr(N);
```
어차피 resize를 할거라면 저는 constructor에서 한 번에하는것을 선호합니다.

2023-04-07 16:51 UTC, Acka1357 commented on Part1_강의자료/Ch05_정렬/문제별코드/18870_좌표압축/18870_map.cpp
> +    for (auto it = mp.begin(); it != mp.end(); it++)
`for (const auto &it : mp)`
second에서 이미 range based for loop을 사용하는데 여기는 안 쓸 이유가 없어보입니다.

2023-04-07 16:51 UTC, Acka1357 commented on Part1_강의자료/Ch05_정렬/문제별코드/1931_회의실배정/1931.cpp
> +}
단어정렬 코멘트와 동일합니다.

2023-04-08 13:07 UTC, Acka1357 approved these changes

2023-04-08 13:07 UTC, merged